import type { Metadata } from "next";
import { Bubblegum_Sans } from "next/font/google";
import "./globals.css";

const bubblegum = Bubblegum_Sans(
  {
    subsets: ["latin"],
    weight: "400"
  }
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bubblegum.className}>{children}</body>
    </html>
  );
}
